### ISSUE TITLE
Some suggested changes for Seed7 FAQ

### ISSUE THREAD

**Issue by celtic-coder** [ThomasMertes/Seed7Home#2]
[comment]: # (https://github.com/ThomasMertes/Seed7Home/issues/??)

Hi Thomas (@ThomasMertes),

As was discussed in the https://github.com/ThomasMertes/seed7/issues/16 issue, I have some suggestions for text changes on the Seed7 FAQ page. I don't know if this is the best format for doing so, but I have attached three separate text files for your consideration:

- "Original"    - A text version of part of the FAQ page
- "Update"      - A modified text version with suggested updates.
- "Patch-Diff7" - A patch file (generated by diff7) showing the differences between the two

The patch file may not be useful since it only shows the differences between the two files that I have generated, rather than the original files used to create the HTML, but it may be helpful in some way.

These are about 40 possible changes, most to them fairly minor. It may be helpful to upload the two files to https://www.textcompare.org/ to see the suggested changes in a colour coded format.

[Original.txt](https://github.com/ThomasMertes/Seed7Home/files/13180850/Original.txt)
[Updated.txt](https://github.com/ThomasMertes/Seed7Home/files/13180853/Updated.txt)
[Patch-Diff7.txt](https://github.com/ThomasMertes/Seed7Home/files/13180854/Patch-Diff7.txt)

Again, if you have some other recommendations on how best to submit possible changes, then I am open to suggestions.

Kind Regards,
Liam

**Comment by ThomasMertes** [comment]
Hi Liam,

I just added your improvements to the Seed7 homepage. Many thanks for providing these changes.

I added the changes manually. I had a diff between "Original" and "Update" in one Emacs. and I added the changes in a second Emacs. Not an optimal approach, but it was successful.

Kind Regards,
Thomas

**Comment by celtic-coder** [comment]
Glad that I was able to help with this. 👍
